# Generated by Django 3.2 on 2021-11-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_id', models.CharField(max_length=3)),
                ('from_id', models.CharField(max_length=3)),
                ('msg', models.CharField(error_messages={'max_length': 'Chat message cannot be more than 500 characters.'}, max_length=500)),
                ('chat_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
