# Generated by Django 3.2 on 2021-10-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='advertise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ad_name', models.CharField(max_length=20)),
                ('ad_content', models.CharField(error_messages={'unique': 'This  content is already exists. Please  enter different content'}, max_length=20, unique=True)),
                ('ad_created', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
