# Generated by Django 3.2.9 on 2021-11-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='friendModel',
            fields=[
                ('FId', models.AutoField(primary_key=True, serialize=False)),
                ('FriendId', models.IntegerField()),
                ('FuserId', models.IntegerField()),
                ('Status', models.IntegerField()),
                ('Friends_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
