# Generated by Django 3.2.9 on 2021-11-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_new',
            name='friendslist',
        ),
        migrations.AddField(
            model_name='users_new',
            name='twoFA',
            field=models.BooleanField(default=False, error_messages={'blank': 'Please choose public or private', 'null': 'make private or public check!!'}),
        ),
        migrations.AlterField(
            model_name='users_new',
            name='mobilenumber',
            field=models.CharField(error_messages={'required': 'Please enter mobile number', 'unique': 'This mobile number is already registered. Please login or enter different mobile number '}, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='users_new',
            name='name',
            field=models.CharField(error_messages={'required': 'Please enter name.'}, max_length=20),
        ),
        migrations.AlterField(
            model_name='users_new',
            name='password',
            field=models.CharField(error_messages={'required': 'Password cannot be null'}, max_length=80),
        ),
    ]
