# Generated by Django 3.2 on 2021-11-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211110_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_new',
            name='twoFA',
            field=models.BooleanField(default=False, error_messages={'blank': 'Please choose If you want 2FA Authentication', 'null': 'make 2FA authentication check!!'}),
        ),
    ]
