# Generated by Django 3.2 on 2021-10-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adv_prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About_me', models.CharField(max_length=25)),
                ('Interest', models.CharField(max_length=25)),
                ('Hobbies', models.CharField(max_length=20)),
                ('Activities', models.CharField(max_length=20)),
                ('Location', models.CharField(max_length=20)),
            ],
        ),
    ]
