# Generated by Django 3.2.9 on 2021-11-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanceProfile', '0002_auto_20211111_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adv_prof',
            name='id',
        ),
        migrations.AddField(
            model_name='adv_prof',
            name='userId',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
