# Generated by Django 3.2.9 on 2021-11-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanceProfile', '0003_auto_20211118_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='adv_prof',
            name='FriendCount',
            field=models.IntegerField(default=0),
        ),
    ]
