# Generated by Django 3.2.9 on 2021-11-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanceProfile', '0004_adv_prof_friendcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adv_prof',
            name='Location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
